Citizen.CreateThread(function()
	AddTextEntry('WT_V_PLANEMSL', 'Missile')
	AddTextEntry('wt_v_flare', 'Flares')
	AddTextEntry('WT_V_AKU_MN', 'Unknown')
	AddTextEntry('WT_V_MIFLARE', 'Flares')
	AddTextEntry('WT_V_FLARE', 'Flares')
	AddTextEntry('WT_V_HUNT_CANN', 'Cannon')
	AddTextEntry('WT_V_R60M', 'R60M')
	AddTextEntry('mig21_bomb', 'Bomb')
	AddTextEntry('MIG23bomb', 'Bomb')
	AddTextEntry('WT_LONGRANGE', 'Missile')
	AddTextEntry('MIR2K_GBU', 'GBU12')
	AddTextEntry('WT_V_mslf', 'Missile')
	AddTextEntry('WT_V_exocet', 'A/G Missile')
	AddTextEntry('WT_V_ROG_CANN', 'Cannon')
	AddTextEntry('SU25_bomb', 'Bomb')
	AddTextEntry('WT_V_SUFLARE', 'Flares')
	AddTextEntry('WT_V_SU57AAM', 'Long Range Missile')
	AddTextEntry('WT_V_KAB500L', 'KAB500L')
	AddTextEntry('WT_V_R73', 'R73')
	AddTextEntry('WT_V_K77M', 'K77M')
	AddTextEntry('WT_V_TUL_MG', 'Unknown')
	AddTextEntry('WT_KH22', 'KH22')
	AddTextEntry('WT_BOMB22', 'Bomb')
	AddTextEntry('WT_V_AIM120', 'AMRAAM')
	AddTextEntry('W_LR_JDAM', 'JDAM')
	AddTextEntry('HARM_MOD', 'AGM-88 HARM')
	AddTextEntry('WT_SFFS', 'SFFS')
	AddTextEntry('WT_AMRAAM', 'AMRAAM')
	AddTextEntry('WT_V_4AGM', 'AGM')
	AddTextEntry('WT_V_SU57AAM', 'Missile')
	AddTextEntry('WT_V_KAB500L', 'KAB500L')
	AddTextEntry('WT_V_R73', 'R73')
	AddTextEntry('WT_V_LZRCAN', 'Cannon')
	AddTextEntry('w_lr_ugb', 'Bomb')
	AddTextEntry('W_LR_SIDEWINDER', 'AIM-9M Sidewinder')
	AddTextEntry('W_LR_PHOENIX', 'AIM-54A Phoenix')
	AddTextEntry('W_LR_SPARROW', 'AIM-7 Sparrow')
	AddTextEntry('WT_VEHBOMB', 'Bomb')
	AddTextEntry('WT_V_SU34MSL', 'Missile')
	AddTextEntry('spear3', 'spear3')
	AddTextEntry('WT_V_HUNT_BARR', 'Rockets')
	AddTextEntry('TLS', 'TLS')
	AddTextEntry('WT_V_DGF_MG', 'Machine Gun')
	AddTextEntry('FAEB', 'FAE-8')
	AddTextEntry('WT_V_GBU27', 'GBU-27')
end)